/*
 * InventoryDateChooserDialog.java
 *
 * Created on May 9, 2008, 12:27 PM
 */

package wlmswingreports;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

/**
 *
 * @author  mdonovan
 */
public class InventoryDateChooserDialog extends javax.swing.JDialog
{
  
  /** Creates new form InventoryDateChooserDialog */
  public InventoryDateChooserDialog(java.awt.Frame parent, boolean modal)
  {
    super(parent, modal);
    initComponents();
  }
  
  public InventoryDateChooserDialog(java.awt.Frame parent, boolean modal, String message)
  {
    super(parent, modal);
    initComponents();
    messageTextField.setText(message);
  }
  
  public Date getSelectedDate()
  {
    Inventory i = (Inventory) invDatesCombo.getSelectedItem();
    return i.date;
  }


  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        invDatesCombo = new JComboBox(getInvDates());
        jButton1 = new javax.swing.JButton();
        messageTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select a Date");

        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        messageTextField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(275, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(messageTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(invDatesCombo, 0, 284, Short.MAX_VALUE))
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(messageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invDatesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
  {//GEN-HEADEREND:event_jButton1ActionPerformed
    this.setVisible(false);
  }//GEN-LAST:event_jButton1ActionPerformed
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      @Override
      public void run()
      {
        InventoryDateChooserDialog dialog = new InventoryDateChooserDialog(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter()
        {
          public void windowClosing(java.awt.event.WindowEvent e)
          {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }
  
  public int getSelectedInventoryId()
  {
    Inventory i = (Inventory) invDatesCombo.getSelectedItem();
    return i.getId();
  }
  
    private class Inventory
  {
    private int id;
    private Date date;
    
    public Inventory(int i, Date d)
    {
      id = i;
      date = d;
    }
    public int getId()
    {
      return id;
    }

    @Override
    public String toString()
    {
      return date.toString();
    }
  }
   private Vector<Inventory> getInvDates()
  {
    Vector<Inventory> iDates = new Vector();
    Connection conn = SessionManager.getConnection();
    String q = "select inventory_id, inventory_date from inventories " +
               "where inventory_major_category_id = "
            + "(select major_category_id from major_categories "
            + "where lower(major_category_name) = 'wine')"
            + " order by inventory_date desc";
      try
      {
        PreparedStatement ps = conn.prepareStatement(q);
        ResultSet rs = ps.executeQuery();
        while (rs.next())
        {
          iDates.add(new Inventory(rs.getInt("inventory_id"), rs.getDate("inventory_date")));
        }
        ps.close();;
        conn.close();
      }
      catch (SQLException ex)
      {
        ex.printStackTrace();
      }
      try
      {
          conn.close();
      }
      catch (SQLException ex)
      {
      Logger.getLogger(InventoryDateChooserDialog.class.getName()).log(Level.SEVERE, null, ex);
      }
    return iDates;
  }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox invDatesCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField messageTextField;
    // End of variables declaration//GEN-END:variables
  
}
