/*
 * UserChooser.java
 *
 * Created on June 10, 2008, 7:43 PM
 */

package wlmswingreports;

import java.util.Vector;


/**
 *
 * @author  Martin Donovan
 */
public class LocationChooser extends javax.swing.JDialog
{
  //private ArrayList<SessionManager.Restaurant> locations = (ArrayList<SessionManager.Restaurant>) SessionManager.getRestaurants();
  private Vector locations = new Vector(SessionManager.getRestaurants());
//private Vector<ConfigFile> locations = new Vector();

  
  /** Creates new form UserChooser */
  public LocationChooser(java.awt.Frame parent, boolean modal)
  {
    super(parent, modal);
    //getLocations();
    initComponents();
  }
  public LocationChooser()
  {
    super(new java.awt.Frame(), true);

    initComponents();
  }

  public LocationChooser(String title) 
  {
    super(new java.awt.Frame(),title, true);  

    initComponents();
  }
  
  
  public String getSelectedLocationName()
  {
    ConfigFile cf = (ConfigFile) locationBox.getSelectedItem();
    return cf.name;
  }
  
  public String getSelectedFileName()
  {
    ConfigFile cf = (ConfigFile) locationBox.getSelectedItem();
    return cf.fileName;
  }

  private class ConfigFile
  {
    public String name;
    public String fileName;
    
    public ConfigFile(String n, String fn)
    {
      name = n;
      fileName = fn;
    }
    
    public String toString()
    {
      return name;
    }
  }
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        locationBox = new javax.swing.JComboBox(locations);
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        locationBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationBoxActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Restaurant");

        userNameTextField.setToolTipText("");

        jLabel2.setText("User Name");

        jLabel3.setText("Password");

        passwordField.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(locationBox, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                        .addComponent(passwordField, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
  {//GEN-HEADEREND:event_jButton1ActionPerformed
     SessionManager.Restaurant selectedRestaurant = (SessionManager.Restaurant) locationBox.getSelectedItem();
    //Session.configFileName = path + selectedRestaurant.fileName;
    //ApplicationData.readConfigurationFile();
    String user = userNameTextField.getText().trim();
    String password = new String(passwordField.getPassword());
      System.out.println(user +  " " + password);
    if(selectedRestaurant.validateRestaurantLogin(user, password)){
        SessionManager.setIsAuthenticated(Boolean.TRUE);
        SessionManager.setActiveRestaurant(selectedRestaurant);
    }
    else{
        SessionManager.setIsAuthenticated(Boolean.FALSE);
    }
    this.dispose();
    //this.setVisible(false);
  }//GEN-LAST:event_jButton1ActionPerformed

private void locationBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationBoxActionPerformed
    SessionManager.Restaurant selectedRestaurant = (SessionManager.Restaurant) locationBox.getSelectedItem();
    SessionManager.setActiveRestaurant(selectedRestaurant);
   //Session.configFileName = path + selectedRestaurant.fileName;
   //ApplicationData.readConfigurationFile();
}//GEN-LAST:event_locationBoxActionPerformed
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        LocationChooser dialog = new LocationChooser(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter()
        {
          public void windowClosing(java.awt.event.WindowEvent e)
          {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox locationBox;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
  
}
