/*
 * UserChooser.java
 *
 * Created on June 10, 2008, 7:43 PM
 */

package wlmswingreports;

import java.io.File;
import java.util.Vector;


/**
 *
 * @author  Martin Donovan
 */
public class LocationChooser extends javax.swing.JDialog
{
  private Vector<ConfigFile> locations = new Vector();
  String path = "";
  String fileName = "lib/locations.txt";
  
  /** Creates new form UserChooser */
  public LocationChooser(java.awt.Frame parent, boolean modal)
  {
    super(parent, modal);
    if ( ! localFileExists())
      path =  "C:/InvBgService/";
    getLocations();
    initComponents();
  }
  public LocationChooser()
  {
    super(new java.awt.Frame(), true);
      if ( ! localFileExists())
    path =  "C:/InvBgService/";
    getLocations();
    initComponents();
  }

  public LocationChooser(String title) 
  {
    super(new java.awt.Frame(),title, true);
    if ( ! localFileExists())
      path =  "C:/InvBgService/";    
    getLocations();
    initComponents();
  }
  
  private boolean localFileExists()
  {
    File f = new File(fileName);
    return f.exists();
  }
  
   public void getLocations()
   {
//    Vector<ConfigFile> cFiles = new Vector();
//    try
//    {
//      //ConfigurationFileReader cf = new ConfigurationFileReader(new File(path + fileName));
//      TreeMap tm = cf.getAll();
//      Iterator iter = tm.entrySet().iterator();
//      while (iter.hasNext())
//      {
//        Map.Entry entry = (Map.Entry) iter.next();
//        cFiles.add(new ConfigFile(entry.getKey().toString(), entry.getValue().toString()));
//      }
//    }
//    catch (FileNotFoundException ex)
//    {
//      ex.printStackTrace();
//    }
//    catch (IOException ex)
//    {
//      ex.printStackTrace();
//    }
//    finally
//    {
//      locations = cFiles;
//    }
   }
  
  public String getSelectedLocationName()
  {
    ConfigFile cf = (ConfigFile) locationBox.getSelectedItem();
    return cf.name;
  }
  
  public String getSelectedFileName()
  {
    ConfigFile cf = (ConfigFile) locationBox.getSelectedItem();
    return cf.fileName;
  }

  private class ConfigFile
  {
    public String name;
    public String fileName;
    
    public ConfigFile(String n, String fn)
    {
      name = n;
      fileName = fn;
    }
    
    public String toString()
    {
      return name;
    }
  }
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        locationBox = new javax.swing.JComboBox(locations);
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        locationBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationBoxActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Please Select a Location");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(locationBox, 0, 273, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(locationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
  {//GEN-HEADEREND:event_jButton1ActionPerformed
    ConfigFile f = (ConfigFile) locationBox.getSelectedItem();
    //Session.configFileName = path + f.fileName;
    //ApplicationData.readConfigurationFile();
    this.dispose();
    //this.setVisible(false);
  }//GEN-LAST:event_jButton1ActionPerformed

private void locationBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationBoxActionPerformed
   ConfigFile f = (ConfigFile) locationBox.getSelectedItem();
   //Session.configFileName = path + f.fileName;
   //ApplicationData.readConfigurationFile();
}//GEN-LAST:event_locationBoxActionPerformed
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        LocationChooser dialog = new LocationChooser(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter()
        {
          public void windowClosing(java.awt.event.WindowEvent e)
          {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox locationBox;
    // End of variables declaration//GEN-END:variables
  
}
