/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wlmswingreports;

import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

/**
 *
 * @author mdonovan
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public MainFrame() {
 
        initComponents();
        //getContentPane().setBackground(Color.yellow);
        setVisible(true);
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        inventoryMenu = new javax.swing.JMenu();
        countSheet = new javax.swing.JMenuItem();
        inventoryExtension = new javax.swing.JMenuItem();
        productLocations = new javax.swing.JMenuItem();
        salesMenu = new javax.swing.JMenu();
        sales = new javax.swing.JMenuItem();
        purchaseMenu = new javax.swing.JMenu();
        invoices = new javax.swing.JMenuItem();
        ordersMenu = new javax.swing.JMenu();
        orders = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.window);
        setPreferredSize(new java.awt.Dimension(1400, 800));

        inventoryMenu.setText("Inventory");

        countSheet.setText("Count Sheet");
        countSheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countSheetActionPerformed(evt);
            }
        });
        inventoryMenu.add(countSheet);

        inventoryExtension.setText("Extension Report");
        inventoryExtension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryExtensionActionPerformed(evt);
            }
        });
        inventoryMenu.add(inventoryExtension);

        productLocations.setText("Product Locations");
        productLocations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productLocationsActionPerformed(evt);
            }
        });
        inventoryMenu.add(productLocations);

        jMenuBar1.add(inventoryMenu);

        salesMenu.setText("Sales");

        sales.setText("Sales Report");
        sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesActionPerformed(evt);
            }
        });
        salesMenu.add(sales);

        jMenuBar1.add(salesMenu);

        purchaseMenu.setText("Purchases");

        invoices.setText("Invoices");
        invoices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoicesActionPerformed(evt);
            }
        });
        purchaseMenu.add(invoices);

        jMenuBar1.add(purchaseMenu);

        ordersMenu.setBackground(new java.awt.Color(204, 204, 0));
        ordersMenu.setText("Orders");

        orders.setText("Order Report");
        orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersActionPerformed(evt);
            }
        });
        ordersMenu.add(orders);

        jMenuBar1.add(ordersMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1275, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void countSheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countSheetActionPerformed
        try {
            JInternalFrame jif = new JInternalFrame("Internal Frame");
            jif.setSize(700, 500);
            jif.setMinimumSize(new Dimension(700, 500));
            //jif.setMaximum(true);
            jif.setMaximizable(true);
            jif.setVisible(true);
            add(jif);
            jif.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_countSheetActionPerformed

    private void inventoryExtensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryExtensionActionPerformed
        try {
            ReportsInventoryExtensionFrame rief = new ReportsInventoryExtensionFrame();
            rief.setVisible(true);
            add(rief);
            rief.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_inventoryExtensionActionPerformed

    private void productLocationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productLocationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productLocationsActionPerformed

    private void salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salesActionPerformed

    private void invoicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoicesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invoicesActionPerformed

    private void ordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordersActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrame().setVisible(true);
//                setBackground(Color.yellow);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem countSheet;
    private javax.swing.JMenuItem inventoryExtension;
    private javax.swing.JMenu inventoryMenu;
    private javax.swing.JMenuItem invoices;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem orders;
    private javax.swing.JMenu ordersMenu;
    private javax.swing.JMenuItem productLocations;
    private javax.swing.JMenu purchaseMenu;
    private javax.swing.JMenuItem sales;
    private javax.swing.JMenu salesMenu;
    // End of variables declaration//GEN-END:variables
}
