/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wlmswingreports;

/**
 *
 * @author mdonovan
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public MainFrame() {
 
        initComponents();
        //getContentPane().setBackground(Color.yellow);
        setVisible(true);
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        inventoryMenu = new javax.swing.JMenu();
        countSheet = new javax.swing.JMenuItem();
        inventoryExtension = new javax.swing.JMenuItem();
        productLocations = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        salesMenu = new javax.swing.JMenu();
        sales = new javax.swing.JMenuItem();
        purchaseMenu = new javax.swing.JMenu();
        invoices = new javax.swing.JMenuItem();
        ordersMenu = new javax.swing.JMenu();
        orders = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.window);
        setPreferredSize(new java.awt.Dimension(1400, 800));

        inventoryMenu.setText("Inventory");

        countSheet.setText("Count Sheet");
        countSheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countSheetActionPerformed(evt);
            }
        });
        inventoryMenu.add(countSheet);

        inventoryExtension.setText("Extension Report");
        inventoryExtension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryExtensionActionPerformed(evt);
            }
        });
        inventoryMenu.add(inventoryExtension);

        productLocations.setText("Product Locations");
        productLocations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productLocationsActionPerformed(evt);
            }
        });
        inventoryMenu.add(productLocations);

        jMenuItem1.setText("Inventory Variance");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryVarianceActionPerformed(evt);
            }
        });
        inventoryMenu.add(jMenuItem1);

        jMenuBar1.add(inventoryMenu);

        salesMenu.setText("Sales");

        sales.setText("Sales Report");
        sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesActionPerformed(evt);
            }
        });
        salesMenu.add(sales);

        jMenuBar1.add(salesMenu);

        purchaseMenu.setText("Purchases");

        invoices.setText("Invoices");
        invoices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoicesActionPerformed(evt);
            }
        });
        purchaseMenu.add(invoices);

        jMenuBar1.add(purchaseMenu);

        ordersMenu.setBackground(new java.awt.Color(204, 204, 0));
        ordersMenu.setText("Orders");

        orders.setText("Order Report");
        orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersActionPerformed(evt);
            }
        });
        ordersMenu.add(orders);

        jMenuBar1.add(ordersMenu);

        jMenu1.setText("Wine List");

        jMenuItem2.setText("BTG List");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wineListBTGActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Club List");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wineListClubListActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem8.setText("Large / Small Format");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wineListLargeSmallFormatActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem4.setText("By Category");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wineListByCategoryActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("By Distributor");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wineListByDistributorActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("By Bin Number");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wineListByBinNumberActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("New Items");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wineListNewProductsActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1275, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void countSheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countSheetActionPerformed
        InventoryPhysicalCountFrame ipcf = new InventoryPhysicalCountFrame();
    }//GEN-LAST:event_countSheetActionPerformed

    private void inventoryExtensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryExtensionActionPerformed
            ReportsInventoryExtensionFrame rief = new ReportsInventoryExtensionFrame();
    }//GEN-LAST:event_inventoryExtensionActionPerformed

    private void productLocationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productLocationsActionPerformed
        ReportsMiscProductLocationsFrame lmplf = new ReportsMiscProductLocationsFrame();
    }//GEN-LAST:event_productLocationsActionPerformed

    private void salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesActionPerformed
       ReportsSalesPeriodCategoryFrame rspcf = new ReportsSalesPeriodCategoryFrame(); 
    }//GEN-LAST:event_salesActionPerformed

    private void invoicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoicesActionPerformed
       ReportsPurchasesPeriodCategoryFrame rppcf = new ReportsPurchasesPeriodCategoryFrame();
    }//GEN-LAST:event_invoicesActionPerformed

    private void ordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersActionPerformed
       ReportsMiscOrderFrame rmof = new ReportsMiscOrderFrame();
    }//GEN-LAST:event_ordersActionPerformed

    private void inventoryVarianceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryVarianceActionPerformed
        ReportsInventoryDiscrepanciesFrame ridf = new ReportsInventoryDiscrepanciesFrame();
    }//GEN-LAST:event_inventoryVarianceActionPerformed

    private void wineListBTGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wineListBTGActionPerformed
        ReportsWineListBTGFrame rwlbtgf = new ReportsWineListBTGFrame();
    }//GEN-LAST:event_wineListBTGActionPerformed

    private void wineListClubListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wineListClubListActionPerformed
        ReportsWineListClubListFrame rwlclf = new ReportsWineListClubListFrame();
    }//GEN-LAST:event_wineListClubListActionPerformed

    private void wineListByCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wineListByCategoryActionPerformed
        ReportsWineListByCategoryFrame rwlbcf = new ReportsWineListByCategoryFrame();
    }//GEN-LAST:event_wineListByCategoryActionPerformed

    private void wineListByDistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wineListByDistributorActionPerformed
        ReportsWineListByDistributorFrame rwlbdf = new ReportsWineListByDistributorFrame();
    }//GEN-LAST:event_wineListByDistributorActionPerformed

    private void wineListByBinNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wineListByBinNumberActionPerformed
        ReportsWineListByBinFrame rwlbbnf = new ReportsWineListByBinFrame();
    }//GEN-LAST:event_wineListByBinNumberActionPerformed

    private void wineListNewProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wineListNewProductsActionPerformed
        ReportsWineListNewProductsFrame rwlnp = new ReportsWineListNewProductsFrame();
    }//GEN-LAST:event_wineListNewProductsActionPerformed

    private void wineListLargeSmallFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wineListLargeSmallFormatActionPerformed
        ReportsWineListLargeSmallFormatFrame rwllsff = new ReportsWineListLargeSmallFormatFrame();
    }//GEN-LAST:event_wineListLargeSmallFormatActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrame().setVisible(true);
//                setBackground(Color.yellow);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem countSheet;
    private javax.swing.JMenuItem inventoryExtension;
    private javax.swing.JMenu inventoryMenu;
    private javax.swing.JMenuItem invoices;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem orders;
    private javax.swing.JMenu ordersMenu;
    private javax.swing.JMenuItem productLocations;
    private javax.swing.JMenu purchaseMenu;
    private javax.swing.JMenuItem sales;
    private javax.swing.JMenu salesMenu;
    // End of variables declaration//GEN-END:variables
}
