/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReportsMiscWineStoriesFrame.java
 *
 * Created on Feb 28, 2010, 6:55:19 PM
 */

package wlmswingreports;

import com.jasperassistant.designer.viewer.ReportViewer;
import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.JInternalFrame;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRField;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author office
 */
public class ReportsWineListNoStoriesFrame extends JInternalFrame
{
    /** Creates new form ReportsMiscWineStoriesFrame */
  public ReportsWineListNoStoriesFrame()
  {
    super();
    getParameters();
    getCols();
    getData();
    initComponents();
    this.setVisible(false);
    setupReport();
  }
  private void getParameters()
  {
    params.put("BUSINESS_NAME", SessionManager.getActiveRestaurant().getRestaurantName());
  }

  private void getCols()
  {
    cols.add("Bin Number");
    cols.add("Product Name");
  }
  private void setupReport()
  {
    try
    {
      rds = new ReportDataSource(cols, data);


       InputStream jasper1 = getClass().getResourceAsStream("WineListNoStoriesReport.jasper");
      JasperReport jasperReport = (JasperReport) net.sf.jasperreports.engine.util.JRLoader.
            loadObject(jasper1);

      JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params, rds);
      //JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params, rds);

      //JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
      JasperViewer.viewReport(jasperPrint, false);
    }

    catch (JRException ex)
    {
      ex.printStackTrace();
    }
  }
    private void getData()
    {
      Connection conn = SessionManager.getConnection();
      String q = "select pi.wine_list_bin_number, " +
                 "pi.inventory_name " +
                 "from product_instances pi, products p " +
                 "where p.product_id = pi.product_id " +
                 "and p.major_category_id = " +
                 "(select major_category_id from major_categories where " +
                 "lower(major_category_name) = 'wine') " +
                 "and pi.active = ? " +
                 "and pi.pos_story is null " +
                 "and wine_list_bin_number is not null " +
                 "order by pi.inventory_name ";

        try
        {
          PreparedStatement ps = conn.prepareStatement(q);
          ps.setBoolean(1, true);
          ResultSet rs = ps.executeQuery();
          while (rs.next())
          {
            Vector<Object> line = new Vector();
            Integer bin = rs.getInt("wine_list_bin_number");
            String iName = rs.getString("inventory_name");
            line.add(bin);
            line.add(iName);
            data.add(line);
          }
          conn.close();
        }
        catch (SQLException ex)
        {
          ex.printStackTrace();
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 225, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 91, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents
  private Vector<Vector<Object>> data = new Vector();
  private Vector<String> cols = new Vector();
  String reportPath = "lib/reports/";
  String compiledReport = reportPath + "WineListNoStoriesReport.jasper";
  String reportSource = reportPath + "WineListNoStoriesReport.jrxml";
  Map<String, Object> params = new HashMap<String, Object>();
  ReportViewer rv = new ReportViewer();
  JasperReport jr = null;
  JasperPrint jp = null;
  net.sf.jasperreports.engine.JRResultSetDataSource ds;
  private ReportDataSource rds;
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
  private class ReportDataSource implements JRDataSource
  {
    Vector<Vector<Object>> data;
    Vector<String> cols;
    int index = -1;

    public ReportDataSource(Vector<String> c, Vector<Vector<Object>> d)
    {
      cols = c;
      data = d;
    }

    @Override
    public boolean next() throws JRException
    {
      index ++;
      return index < data.size();
    }

    public int getColIndex(JRField colName)
    {
      String cn = colName.getName();
      int colIndex = -1;
      for (int i = 0; i < cols.size(); i ++)
      {
        //System.out.println("cols " + cols.elementAt(i));
        if (cn.equals(cols.elementAt(i)))
         colIndex = i;
      }
      return colIndex;
    }

    @Override
    public Object getFieldValue(JRField colName) throws JRException
    {
      String cName = colName.getName();
      int c = getColIndex(colName);
      if (c != -1 && index < data.size() && c < data.elementAt(index).size())
      {
        Object o = data.elementAt(index).elementAt(c);
        if (o != null)
        {
          if ("Bin Number".equals(cName) )
          {
            return (Integer) o;
          }
          else if ("Has Story".equals(cName) || "Has Image".equals(cName))
          {
            return (Boolean) o;
          }
          else
            return o.toString();
        }
        else
          return null;
      }
      else
        return null;
    }
  }
}
